name : ReleaseCI
on: 
  push:
    branches: ["main"]
    paths: ["DCE/**"]
jobs:
  detect-file-changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      dce: ${{ steps.filter.outputs.dce }}
    steps:
      - name: Checkout Backend code
        uses: actions/checkout@v1
      # For pull requests it's not necessary to checkout the code
      - name: Apply filters to check file(s) cahnges
        uses: actions/checkout@v1
        id: filter
        with:
          filters: |
            dce:
              - 'DCE/**'
  dce:
    needs: [detect-file-changes]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Release to S3
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_Bucket_Name}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_Access_Key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_Access_Secret}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_Default_Region}}
        run: |
          
          sudo apt-get install awscli
          echo $aws --version
          zip -r dce.zip DCE/
          aws s3 sync dce.zip s3:://${{secrets.AWS_Bucket_Name}}
        